import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import githublink from "../public/github.png";
import profilePicture from "../public/profile.jpeg";
import SkillProgressBar from "../components/SkillProgressBar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowDown, faChevronDown } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Kirkerud.dev</h1>

      <main className={styles.main}>
        <div id="intro" className={styles.section}>
          <div className={styles.grid}>
            <div className={styles.glassCard}>
              <Image
                src={profilePicture}
                width={300}
                height={300}
                alt="profile"
              />

              <p className={styles.description}>
                Hello! My name is Kristoffer, i am a fullstack developer from
                Gothenburg, Sweden. I love everything tech related and
              </p>
            </div>
            <div className={styles.iconContainer}>
              <FontAwesomeIcon
                className={styles.regularIcon}
                icon={faChevronDown}
              />
            </div>

            <div className={styles.sectionContent}></div>
          </div>
        </div>
        <div id="skills" className={styles.section}>
          <div className="justify-center text-white font-bold">
            <h1>Skillsets</h1>
          </div>
          <div className={styles.groupedGrid}>
            <div className={styles.glassCard}>
              <h2>Frontend</h2>
              <SkillProgressBar title="React.js" progress={4} />
              <SkillProgressBar title="HTML" progress={4} />
            </div>
            <div className={styles.glassCard}>
              <h2>Backend</h2>
              <SkillProgressBar title="C#" progress={3} />
              <SkillProgressBar title="Python" progress={2} />
              <SkillProgressBar title="Java" progress={2} />
            </div>
            <div className={styles.glassCard}>
              <h2>Cloud</h2>
              <SkillProgressBar title="Sharepoint" progress={3} />
              <SkillProgressBar title="Azure" progress={3} />
              <SkillProgressBar title="Google Domains" progress={3} />
            </div>
            <div className={styles.glassCard}>
              <h2>Tools</h2>
              <SkillProgressBar title="Docker" progress={4} />
              <SkillProgressBar title="VSCode" progress={5} />
              <SkillProgressBar title="Photoshop" progress={2} />
            </div>
          </div>
        </div>
      </main>

      {/*  <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noreferrer"
          href="https://github.com/Kristofferkirk"
        >
          <Image width={50} height={50} alt="github" src={githublink} />
        </a>
      </footer> */}
    </div>
  );
}
